name: strainer2_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - biopython>1.8
  - plotly
  - pip
  - pyrodigal
  - pandas
  - nbformat
  - zlib
  - make
  - pyarrow
  - pyahocorasick
  - python-kaleido=0.2.1
  - ncbi-datasets-cli
  - snakemake
  - sourmash
  - sourmash_plugin_branchwater
  - polars
  #- pip:
  #  - kaleido

